### ISSUE TITLE
NullPointerException при Autowire-нато repo - Unit testing

### ISSUE THREAD

**Issue by ivaylo-traykov** [luchob/softuni-spring-advanced-2021#17]
Здравей, Лъчо!

Не съм сигурен дали отварянето на issues още е актуално, но ще го пусна все пак. Започнах опити да пиша тестове и още с първия се сблъсках с NullPointerException хвърлен от репо, което трбява да е autowire-нато. Опитвам се да тествам контролер, като следвах твоята демонстрация от видеото, което е качено на курса. Опитал съм да настроя in-memory база данни - hsql (не знам до колко е успешно и това).

Опитах да потърся решение в интернет, но не много успешно.

Всичко може да видиш тук - https://github.com/ivaylo-traykov/softuni-final-project

Поздрави,
Иво

**Comment by luchob** [comment]
Здравей!

Забелязвам доста проблеми. Нека ги почнем поред и например да настроим H2 база, като че ли съм свикнал повечко с нея.

1. Добавяне на правилните депендънсита в pom.xml

Махаме hsql и добавяме h2. Така:

```
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>test</scope>
		</dependency>
```

2. Махаме всякакви JDBC драйвъри и т.н. от **тестовия** `application.yaml`. Ето така:

```
spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        database-platform: org.hibernate.dialect.H2Dialect
```

3. За да вдигнеш контекста на спринг в тестовия `application.yaml` добавяме настройки за клаудинари, иначе ще се оплаче. Например:

```
cloudinary:
    cloud-name: test
    api-key: test
    api-secret: test
```

4. Продължаваме с оправянето на теста. Там са омешани JUnit 4 и JUnit 5 анотации. Това са правилните импорти за JUnit5:

```
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
```

Нищо повече. `Before` става `BeforeEach`

5. Тъй като теста ти удря секюрнат ендпойнт трябва да му добавим `WithMockUser`. Например:

```
    @WithMockUser(username = "pesho", roles = {"ADMIN"})
    @Test
    public void testCommentsGetReturnsCorrectStatus() throws Exception {
        this.mockMvc.perform(get("/comments/pages?page=0"))
                .andExpect(status().isOk());
    }
```

6. 
<img width="471" alt="Screenshot 2021-04-06 at 8 48 28" src="https://user-images.githubusercontent.com/10339738/113664687-dfec0a00-96b4-11eb-8e27-dd01be1f0c51.png">


Надявам се да съм помогнал :-)
Л.
